name: Noida-Daily-Check

# This global 'env' at the top is the KEY to stopping the error
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    # Runs at 15:15 IST (NPL Update)
    - cron: '15 9 * * *'    
    # Runs 20:00, 21:00, 22:00 IST (Noida Peak Window)
    - cron: '30 14,15,16 * * *' 
  workflow_dispatch: 

jobs:
  check-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Run Monitor
        # This gives your script the SendGrid key you saved in 'Secrets'
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          pip install requests
          python monitor.py
