name: Noida-Daily-Check
on:
  schedule:
    - cron: '15 9 * * *'    # Runs at 14:45 IST (After NPL report)
    - cron: '30 14,15,16 * * *' # Runs every hour during Noida danger window (20:00-22:00 IST)
  workflow_dispatch:        # Allows you to click a button to run it anytime
jobs:
  check-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Monitor
        run: |
          pip install requests
          python monitor.py
